name: Weekly News Scraper

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run scraper
      run: python news_scraper.py
    # Add steps here to send output to AI, save .json or .html, or email
