name: Weekly News Scraper

on:
  schedule:
    # Runs at 6am UTC every Sunday
    - cron: '0 6 * * 0'
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run news scraper
      run: |
        python news_scraper.py

    - name: Upload scraped data (CSV and JSON)
      uses: actions/upload-artifact@v4
      with:
        name: scraped-news-data
        path: |
          scraped_data/*.csv
          scraped_data/*.json
          scraped_data/chunks/*.json
