name: Weekly News Scraper & Claude Analysis

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  scrape-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Scrape all non-Radio-Canada sites
      run: |
        python combined_scraper.py --exclude-rc

    - name: Analyze scraped news with Claude
      env:
        CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: |
        sed -i "s/claude-3-5-sonnet-20241022/claude-sonnet-4-20250514/g" analyze_with_claude_single.py
        python analyze_with_claude_single.py

    - name: Debug: list outputs on disk
      run: |
        pwd
        echo "---- root ----"; ls -la
        echo "---- scraped_data ----"; ls -la scraped_data || true
        echo "---- analysis ----"; ls -la analysis || true

    # If you want the mailer to keep its old pattern, keep this copy step.
    - name: Prepare analysis file for email script
      run: |
        set -e
        mkdir -p scraped_data
        LATEST=$(ls -t analysis/claude_analysis_*.txt | head -n 1)
        cp "$LATEST" "scraped_data/$(date +%Y%m%d)_claude_analysis.txt"
        echo "Prepared: scraped_data/$(date +%Y%m%d)_claude_analysis.txt"
        ls -la scraped_data

    - name: Email latest analysis results
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        python send_analysis_email_Version2.py

    - name: Upload results as workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: news-analysis-results
        path: |
          scraped_data/news_articles_*.json
          analysis/*.txt
          scraped_data/*_claude_analysis.txt
